### ISSUE TITLE
Telnet unable to format event

### ISSUE THREAD

**Issue by seisatsu** [seisatsu/Dennis#70]
Sometimes when trying to send a traceback to the client, Telnet gets the error "Unable to format event".

Example:
```2020-06-30T08:23:19-0700 [telnet#error] Unable to format event {'log_logger': <Logger 'telnet'>, 'log_level': <LogLevel=error>, 'log_namespace': 'telnet', 'log_source': None, 'log_format': 'Traceback (most recent call last):\n  File "/home/seisatsu/Source/Dennis/telnet.py", line 88, in lineReceived\n    self.factory.router.shell.command(self.factory.router[self.peer]["console"], line)\n  File "/home/seisatsu/Source/Dennis/shell.py", line 200, in command\n    return self._call(console, \' \'.join(line).lower(), [])\n  File "/home/seisatsu/Source/Dennis/shell.py", line 405, in _call\n    return self._commands[command].COMMAND(console, args)\n  File "/home/seisatsu/Source/Dennis/commands/shutdown.py", line 59, in COMMAND\n    console.router._config["shutdown_delay"]))\nValueError: Single \'}\' encountered in format string\n', 'log_time': 1593530599.251825}: Single '}' encountered in format string```

**Comment by seisatsu** [comment]
Oh, it's literally the logger trying and failing to **format** an event because of a curly brace mismatch. That's normal.

**Comment by seisatsu** [comment]
Nevermind, this happens other times too. Looks like a Twisted bug.

**Comment by seisatsu** [comment]
Should be obviated by replacing the Twisted Logger in  308f72b.
